eureka:
  instance:
    hostname: peer2
    appname: eureka-service
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 30
    metadataMap:
      instanceId: ${server.port}

  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
    registerWithEureka: true
    fetchRegistry: true

  server:
    enable-self-preservation: true

server:
  port: 1112
