eureka:
  instance:
    hostname: peer1
    appname: eureka-service
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 30
    metadataMap:
      instanceId: ${server.port}
      
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
    registerWithEureka: true
    fetchRegistry: true

  server:
    enable-self-preservation: true

server:
  port: 1111
